-- CreateTable
CREATE TABLE "users" (
    "id" SERIAL NOT NULL,
    "email" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "nama" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'admin',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "markas_pmi" (
    "id" SERIAL NOT NULL,
    "nama_pmi" TEXT NOT NULL,
    "level_pmi" TEXT NOT NULL,
    "nama_kepala_markas" TEXT NOT NULL,
    "no_telpon" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "kode_pos" TEXT NOT NULL,
    "alamat" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "markas_pmi_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "unit_pmr" (
    "id" SERIAL NOT NULL,
    "kode_unit" TEXT,
    "nama_unit" TEXT NOT NULL,
    "alamat" TEXT,
    "email" TEXT,
    "no_telpon" TEXT,
    "status" TEXT NOT NULL DEFAULT 'Aktif',
    "tingkat" TEXT NOT NULL,
    "provinsi" TEXT,
    "kabupaten" TEXT,
    "sk" TEXT,
    "lat" DOUBLE PRECISION,
    "lng" DOUBLE PRECISION,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "unit_pmr_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "unit_ksr" (
    "id" SERIAL NOT NULL,
    "kode_unit" TEXT,
    "nama_unit" TEXT NOT NULL,
    "alamat" TEXT,
    "email" TEXT,
    "no_telpon" TEXT,
    "status" TEXT NOT NULL DEFAULT 'Aktif',
    "jenis" TEXT NOT NULL,
    "kategori" TEXT,
    "provinsi" TEXT,
    "kabupaten" TEXT,
    "catatan" TEXT,
    "sk" TEXT,
    "lat" DOUBLE PRECISION,
    "lng" DOUBLE PRECISION,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "unit_ksr_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "unit_tsr" (
    "id" SERIAL NOT NULL,
    "kode_unit" TEXT,
    "nama_unit" TEXT NOT NULL,
    "alamat" TEXT,
    "email" TEXT,
    "no_telpon" TEXT,
    "status" TEXT NOT NULL DEFAULT 'Aktif',
    "jenis" TEXT NOT NULL,
    "provinsi" TEXT,
    "kabupaten" TEXT,
    "sk" TEXT,
    "lat" DOUBLE PRECISION,
    "lng" DOUBLE PRECISION,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "unit_tsr_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "anggota_pmr" (
    "id" SERIAL NOT NULL,
    "provinsi" TEXT NOT NULL,
    "kabupaten" TEXT NOT NULL,
    "angkatan" INTEGER NOT NULL,
    "kode_anggota" TEXT NOT NULL,
    "nama" TEXT NOT NULL,
    "kelamin" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Aktif',
    "kategori" TEXT NOT NULL DEFAULT 'Anggota',
    "nama_unit" TEXT NOT NULL,
    "jenis" TEXT NOT NULL,
    "jenis_identitas" TEXT,
    "no_nik" TEXT,
    "tempat_lahir" TEXT,
    "tanggal_lahir" TEXT,
    "agama" TEXT,
    "golongan_darah" TEXT,
    "email" TEXT,
    "no_hp" TEXT,
    "alamat_ktp" TEXT,
    "ktp_provinsi" TEXT,
    "ktp_kabupaten" TEXT,
    "ktp_kecamatan" TEXT,
    "ktp_desa" TEXT,
    "dom_is_alamat_ktp" BOOLEAN DEFAULT false,
    "dom_provinsi" TEXT,
    "dom_kabupaten" TEXT,
    "dom_kecamatan" TEXT,
    "dom_desa" TEXT,
    "alamat" TEXT,
    "rt" TEXT,
    "rw" TEXT,
    "kode_pos" TEXT,
    "no_telp" TEXT,
    "dom_status_kepemilikan" TEXT,
    "dom_status_tinggal" TEXT,
    "dom_catatan" TEXT,
    "id_provinsi" TEXT,
    "id_kabupaten" TEXT,
    "id_kecamatan" TEXT,
    "id_desa" TEXT,
    "id_alamat" TEXT,
    "id_rt" TEXT,
    "id_rw" TEXT,
    "id_kode_pos" TEXT,
    "id_status_kepemilikan" TEXT,
    "foto" TEXT,
    "kontak_darurat_nama" TEXT,
    "kontak_darurat_hubungan" TEXT,
    "kontak_darurat_hp" TEXT,
    "kontak_darurat_alamat" TEXT,
    "riwayat_tahun_bergabung" TEXT,
    "riwayat_unit_asal" TEXT,
    "riwayat_jabatan" TEXT,
    "riwayat_keterangan" TEXT,
    "pendidikan_tingkat" TEXT,
    "pendidikan_institusi" TEXT,
    "pendidikan_jurusan" TEXT,
    "pendidikan_tahun_lulus" TEXT,
    "pendidikan_ijazah" TEXT,
    "diklat_nama" TEXT,
    "diklat_penyelenggara" TEXT,
    "diklat_tempat" TEXT,
    "diklat_tahun" TEXT,
    "diklat_sertifikat" TEXT,
    "sertifikasi_nama" TEXT,
    "sertifikasi_penerbit" TEXT,
    "sertifikasi_nomor" TEXT,
    "sertifikasi_tahun" TEXT,
    "sertifikasi_berlaku" TEXT,
    "keahlian" TEXT,
    "keterampilan" TEXT,
    "keahlian_kategori" TEXT,
    "organisasi_nama" TEXT,
    "organisasi_jabatan" TEXT,
    "organisasi_periode" TEXT,
    "organisasi_keterangan" TEXT,
    "penghargaan_nama" TEXT,
    "penghargaan_pemberi" TEXT,
    "penghargaan_tahun" TEXT,
    "penghargaan_keterangan" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "anggota_pmr_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "anggota_ksr" (
    "id" SERIAL NOT NULL,
    "provinsi" TEXT NOT NULL,
    "kabupaten" TEXT NOT NULL,
    "angkatan" INTEGER NOT NULL,
    "kode_anggota" TEXT NOT NULL,
    "nama" TEXT NOT NULL,
    "kelamin" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Aktif',
    "kategori" TEXT NOT NULL DEFAULT 'Anggota',
    "nama_unit" TEXT NOT NULL,
    "jenis" TEXT NOT NULL,
    "jenis_identitas" TEXT,
    "no_nik" TEXT,
    "tempat_lahir" TEXT,
    "tanggal_lahir" TEXT,
    "agama" TEXT,
    "golongan_darah" TEXT,
    "email" TEXT,
    "no_hp" TEXT,
    "alamat_ktp" TEXT,
    "ktp_provinsi" TEXT,
    "ktp_kabupaten" TEXT,
    "ktp_kecamatan" TEXT,
    "ktp_desa" TEXT,
    "dom_is_alamat_ktp" BOOLEAN DEFAULT false,
    "dom_provinsi" TEXT,
    "dom_kabupaten" TEXT,
    "dom_kecamatan" TEXT,
    "dom_desa" TEXT,
    "alamat" TEXT,
    "rt" TEXT,
    "rw" TEXT,
    "kode_pos" TEXT,
    "no_telp" TEXT,
    "dom_status_kepemilikan" TEXT,
    "dom_status_tinggal" TEXT,
    "dom_catatan" TEXT,
    "id_provinsi" TEXT,
    "id_kabupaten" TEXT,
    "id_kecamatan" TEXT,
    "id_desa" TEXT,
    "id_alamat" TEXT,
    "id_rt" TEXT,
    "id_rw" TEXT,
    "id_kode_pos" TEXT,
    "id_status_kepemilikan" TEXT,
    "foto" TEXT,
    "kontak_darurat_nama" TEXT,
    "kontak_darurat_hubungan" TEXT,
    "kontak_darurat_hp" TEXT,
    "kontak_darurat_alamat" TEXT,
    "riwayat_tahun_bergabung" TEXT,
    "riwayat_unit_asal" TEXT,
    "riwayat_jabatan" TEXT,
    "riwayat_keterangan" TEXT,
    "pendidikan_tingkat" TEXT,
    "pendidikan_institusi" TEXT,
    "pendidikan_jurusan" TEXT,
    "pendidikan_tahun_lulus" TEXT,
    "pendidikan_ijazah" TEXT,
    "diklat_nama" TEXT,
    "diklat_penyelenggara" TEXT,
    "diklat_tempat" TEXT,
    "diklat_tahun" TEXT,
    "diklat_sertifikat" TEXT,
    "sertifikasi_nama" TEXT,
    "sertifikasi_penerbit" TEXT,
    "sertifikasi_nomor" TEXT,
    "sertifikasi_tahun" TEXT,
    "sertifikasi_berlaku" TEXT,
    "keahlian" TEXT,
    "keterampilan" TEXT,
    "keahlian_kategori" TEXT,
    "organisasi_nama" TEXT,
    "organisasi_jabatan" TEXT,
    "organisasi_periode" TEXT,
    "organisasi_keterangan" TEXT,
    "penghargaan_nama" TEXT,
    "penghargaan_pemberi" TEXT,
    "penghargaan_tahun" TEXT,
    "penghargaan_keterangan" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "anggota_ksr_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "anggota_tsr" (
    "id" SERIAL NOT NULL,
    "provinsi" TEXT NOT NULL,
    "kabupaten" TEXT NOT NULL,
    "angkatan" INTEGER NOT NULL,
    "kode_anggota" TEXT NOT NULL,
    "nama" TEXT NOT NULL,
    "kelamin" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Aktif',
    "kategori" TEXT NOT NULL DEFAULT 'Anggota',
    "nama_unit" TEXT NOT NULL,
    "jenis" TEXT NOT NULL,
    "jenis_identitas" TEXT,
    "no_nik" TEXT,
    "tempat_lahir" TEXT,
    "tanggal_lahir" TEXT,
    "agama" TEXT,
    "golongan_darah" TEXT,
    "email" TEXT,
    "no_hp" TEXT,
    "alamat_ktp" TEXT,
    "ktp_provinsi" TEXT,
    "ktp_kabupaten" TEXT,
    "ktp_kecamatan" TEXT,
    "ktp_desa" TEXT,
    "dom_is_alamat_ktp" BOOLEAN DEFAULT false,
    "dom_provinsi" TEXT,
    "dom_kabupaten" TEXT,
    "dom_kecamatan" TEXT,
    "dom_desa" TEXT,
    "alamat" TEXT,
    "rt" TEXT,
    "rw" TEXT,
    "kode_pos" TEXT,
    "no_telp" TEXT,
    "dom_status_kepemilikan" TEXT,
    "dom_status_tinggal" TEXT,
    "dom_catatan" TEXT,
    "id_provinsi" TEXT,
    "id_kabupaten" TEXT,
    "id_kecamatan" TEXT,
    "id_desa" TEXT,
    "id_alamat" TEXT,
    "id_rt" TEXT,
    "id_rw" TEXT,
    "id_kode_pos" TEXT,
    "id_status_kepemilikan" TEXT,
    "foto" TEXT,
    "kontak_darurat_nama" TEXT,
    "kontak_darurat_hubungan" TEXT,
    "kontak_darurat_hp" TEXT,
    "kontak_darurat_alamat" TEXT,
    "riwayat_tahun_bergabung" TEXT,
    "riwayat_unit_asal" TEXT,
    "riwayat_jabatan" TEXT,
    "riwayat_keterangan" TEXT,
    "pendidikan_tingkat" TEXT,
    "pendidikan_institusi" TEXT,
    "pendidikan_jurusan" TEXT,
    "pendidikan_tahun_lulus" TEXT,
    "pendidikan_ijazah" TEXT,
    "diklat_nama" TEXT,
    "diklat_penyelenggara" TEXT,
    "diklat_tempat" TEXT,
    "diklat_tahun" TEXT,
    "diklat_sertifikat" TEXT,
    "sertifikasi_nama" TEXT,
    "sertifikasi_penerbit" TEXT,
    "sertifikasi_nomor" TEXT,
    "sertifikasi_tahun" TEXT,
    "sertifikasi_berlaku" TEXT,
    "keahlian" TEXT,
    "keterampilan" TEXT,
    "keahlian_kategori" TEXT,
    "organisasi_nama" TEXT,
    "organisasi_jabatan" TEXT,
    "organisasi_periode" TEXT,
    "organisasi_keterangan" TEXT,
    "penghargaan_nama" TEXT,
    "penghargaan_pemberi" TEXT,
    "penghargaan_tahun" TEXT,
    "penghargaan_keterangan" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "anggota_tsr_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "anggota_dds" (
    "id" SERIAL NOT NULL,
    "provinsi" TEXT NOT NULL,
    "kabupaten" TEXT NOT NULL,
    "angkatan" INTEGER NOT NULL,
    "kode_anggota" TEXT NOT NULL,
    "nama" TEXT NOT NULL,
    "kelamin" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Aktif',
    "kategori" TEXT NOT NULL DEFAULT 'Anggota',
    "nama_unit" TEXT NOT NULL,
    "jenis" TEXT NOT NULL,
    "jenis_identitas" TEXT,
    "no_nik" TEXT,
    "tempat_lahir" TEXT,
    "tanggal_lahir" TEXT,
    "agama" TEXT,
    "golongan_darah" TEXT,
    "email" TEXT,
    "no_hp" TEXT,
    "alamat_ktp" TEXT,
    "ktp_provinsi" TEXT,
    "ktp_kabupaten" TEXT,
    "ktp_kecamatan" TEXT,
    "ktp_desa" TEXT,
    "dom_is_alamat_ktp" BOOLEAN DEFAULT false,
    "dom_provinsi" TEXT,
    "dom_kabupaten" TEXT,
    "dom_kecamatan" TEXT,
    "dom_desa" TEXT,
    "alamat" TEXT,
    "rt" TEXT,
    "rw" TEXT,
    "kode_pos" TEXT,
    "no_telp" TEXT,
    "dom_status_kepemilikan" TEXT,
    "dom_status_tinggal" TEXT,
    "dom_catatan" TEXT,
    "id_provinsi" TEXT,
    "id_kabupaten" TEXT,
    "id_kecamatan" TEXT,
    "id_desa" TEXT,
    "id_alamat" TEXT,
    "id_rt" TEXT,
    "id_rw" TEXT,
    "id_kode_pos" TEXT,
    "id_status_kepemilikan" TEXT,
    "foto" TEXT,
    "kontak_darurat_nama" TEXT,
    "kontak_darurat_hubungan" TEXT,
    "kontak_darurat_hp" TEXT,
    "kontak_darurat_alamat" TEXT,
    "riwayat_tahun_bergabung" TEXT,
    "riwayat_unit_asal" TEXT,
    "riwayat_jabatan" TEXT,
    "riwayat_keterangan" TEXT,
    "pendidikan_tingkat" TEXT,
    "pendidikan_institusi" TEXT,
    "pendidikan_jurusan" TEXT,
    "pendidikan_tahun_lulus" TEXT,
    "pendidikan_ijazah" TEXT,
    "diklat_nama" TEXT,
    "diklat_penyelenggara" TEXT,
    "diklat_tempat" TEXT,
    "diklat_tahun" TEXT,
    "diklat_sertifikat" TEXT,
    "sertifikasi_nama" TEXT,
    "sertifikasi_penerbit" TEXT,
    "sertifikasi_nomor" TEXT,
    "sertifikasi_tahun" TEXT,
    "sertifikasi_berlaku" TEXT,
    "keahlian" TEXT,
    "keterampilan" TEXT,
    "keahlian_kategori" TEXT,
    "organisasi_nama" TEXT,
    "organisasi_jabatan" TEXT,
    "organisasi_periode" TEXT,
    "organisasi_keterangan" TEXT,
    "penghargaan_nama" TEXT,
    "penghargaan_pemberi" TEXT,
    "penghargaan_tahun" TEXT,
    "penghargaan_keterangan" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "anggota_dds_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "bencana" (
    "id" SERIAL NOT NULL,
    "jenis_bencana" TEXT NOT NULL,
    "nama_kejadian" TEXT NOT NULL,
    "tanggal_kejadian" TEXT NOT NULL,
    "id_provinsi" INTEGER,
    "level" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Kejadian',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "bencana_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "kegiatan" (
    "id" SERIAL NOT NULL,
    "tanggal_kejadian" TEXT NOT NULL,
    "nama_kegiatan" TEXT NOT NULL,
    "tempat" TEXT NOT NULL,
    "bidang" TEXT NOT NULL,
    "bulan" TEXT NOT NULL,
    "semester" INTEGER NOT NULL,
    "tahun" INTEGER NOT NULL,
    "ks_count" INTEGER NOT NULL DEFAULT 0,
    "tsr_count" INTEGER NOT NULL DEFAULT 0,
    "pengurus_count" INTEGER NOT NULL DEFAULT 0,
    "staf_count" INTEGER NOT NULL DEFAULT 0,
    "pmr_count" INTEGER NOT NULL DEFAULT 0,
    "penerima_laki" INTEGER NOT NULL DEFAULT 0,
    "penerima_perempuan" INTEGER NOT NULL DEFAULT 0,
    "penerima_kk" INTEGER NOT NULL DEFAULT 0,
    "penerima_jiwa" INTEGER NOT NULL DEFAULT 0,
    "keterangan" TEXT,
    "anggaran" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "kegiatan_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "relawan" (
    "id" SERIAL NOT NULL,
    "provinsi" TEXT NOT NULL,
    "kabupaten" TEXT NOT NULL,
    "angkatan" INTEGER NOT NULL,
    "kode_anggota" TEXT NOT NULL,
    "nama" TEXT NOT NULL,
    "kelamin" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Aktif',
    "kategori" TEXT NOT NULL DEFAULT 'Anggota',
    "nama_unit" TEXT NOT NULL,
    "jenis" TEXT NOT NULL,
    "jenis_identitas" TEXT,
    "no_nik" TEXT,
    "tempat_lahir" TEXT,
    "tanggal_lahir" TEXT,
    "agama" TEXT,
    "golongan_darah" TEXT,
    "email" TEXT,
    "no_hp" TEXT,
    "alamat_ktp" TEXT,
    "ktp_provinsi" TEXT,
    "ktp_kabupaten" TEXT,
    "ktp_kecamatan" TEXT,
    "ktp_desa" TEXT,
    "dom_is_alamat_ktp" BOOLEAN DEFAULT false,
    "dom_provinsi" TEXT,
    "dom_kabupaten" TEXT,
    "dom_kecamatan" TEXT,
    "dom_desa" TEXT,
    "alamat" TEXT,
    "rt" TEXT,
    "rw" TEXT,
    "kode_pos" TEXT,
    "no_telp" TEXT,
    "dom_status_kepemilikan" TEXT,
    "dom_status_tinggal" TEXT,
    "dom_catatan" TEXT,
    "id_provinsi" TEXT,
    "id_kabupaten" TEXT,
    "id_kecamatan" TEXT,
    "id_desa" TEXT,
    "id_alamat" TEXT,
    "id_rt" TEXT,
    "id_rw" TEXT,
    "id_kode_pos" TEXT,
    "id_status_kepemilikan" TEXT,
    "foto" TEXT,
    "kontak_darurat_nama" TEXT,
    "kontak_darurat_hubungan" TEXT,
    "kontak_darurat_hp" TEXT,
    "kontak_darurat_alamat" TEXT,
    "riwayat_tahun_bergabung" TEXT,
    "riwayat_unit_asal" TEXT,
    "riwayat_jabatan" TEXT,
    "riwayat_keterangan" TEXT,
    "pendidikan_tingkat" TEXT,
    "pendidikan_institusi" TEXT,
    "pendidikan_jurusan" TEXT,
    "pendidikan_tahun_lulus" TEXT,
    "pendidikan_ijazah" TEXT,
    "diklat_nama" TEXT,
    "diklat_penyelenggara" TEXT,
    "diklat_tempat" TEXT,
    "diklat_tahun" TEXT,
    "diklat_sertifikat" TEXT,
    "sertifikasi_nama" TEXT,
    "sertifikasi_penerbit" TEXT,
    "sertifikasi_nomor" TEXT,
    "sertifikasi_tahun" TEXT,
    "sertifikasi_berlaku" TEXT,
    "keahlian" TEXT,
    "keterampilan" TEXT,
    "keahlian_kategori" TEXT,
    "organisasi_nama" TEXT,
    "organisasi_jabatan" TEXT,
    "organisasi_periode" TEXT,
    "organisasi_keterangan" TEXT,
    "penghargaan_nama" TEXT,
    "penghargaan_pemberi" TEXT,
    "penghargaan_tahun" TEXT,
    "penghargaan_keterangan" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "relawan_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "roster" (
    "id" SERIAL NOT NULL,
    "kode_anggota" TEXT NOT NULL,
    "nama" TEXT NOT NULL,
    "unit" TEXT NOT NULL,
    "jenis" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "roster_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "captcha" (
    "id" SERIAL NOT NULL,
    "code" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "captcha_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "unit_pmr_kode_unit_key" ON "unit_pmr"("kode_unit");

-- CreateIndex
CREATE UNIQUE INDEX "unit_ksr_kode_unit_key" ON "unit_ksr"("kode_unit");

-- CreateIndex
CREATE UNIQUE INDEX "unit_tsr_kode_unit_key" ON "unit_tsr"("kode_unit");

-- CreateIndex
CREATE UNIQUE INDEX "anggota_pmr_kode_anggota_key" ON "anggota_pmr"("kode_anggota");

-- CreateIndex
CREATE UNIQUE INDEX "anggota_ksr_kode_anggota_key" ON "anggota_ksr"("kode_anggota");

-- CreateIndex
CREATE UNIQUE INDEX "anggota_tsr_kode_anggota_key" ON "anggota_tsr"("kode_anggota");

-- CreateIndex
CREATE UNIQUE INDEX "anggota_dds_kode_anggota_key" ON "anggota_dds"("kode_anggota");

-- CreateIndex
CREATE UNIQUE INDEX "relawan_kode_anggota_key" ON "relawan"("kode_anggota");

